export const CLEAR_SCHEDULES = 'CLEAR_SCHEDULES';
export const CLEAR_SELECTED_DATE = 'CLEAR_SELECTED_DATE';
export const SAVE_SCHEDULES = 'SAVE_SCHEDULES';
export const SAVE_SELECTED_DATE = 'SAVE_SELECTED_DATE';
