export enum ACTION_TYPES {
  CLEAR_PROVIDER_PROFILE = 'CLEAR_PROVIDER_PROFILE',
  CLEAR_SCHEDULES = 'CLEAR_SCHEDULES',
  CLEAR_SELECTED_DATE = 'CLEAR_SELECTED_DATE',
  CLEAR_SELECTED_DAY_PART = 'CLEAR_SELECTED_DAY_PART',
  CLEAR_SELECTED_TIME_ID = 'CLEAR_SELECTED_TIME_ID',
  SAVE_PROVIDER_PROFILE = 'SAVE_PROVIDER_PROFILE',
  SAVE_SCHEDULES = 'SAVE_SCHEDULES',
  SAVE_SELECTED_DATE = 'SAVE_SELECTED_DATE',
  SAVE_SELECTED_DAY_PART = 'SAVE_SELECTED_DAY_PART',
  SAVE_SELECTED_TIME_ID = 'SAVE_SELECTED_TIME_ID',
  TOGGLE_SHOWING_CALENDAR = 'TOGGLE_SHOWING_CALENDAR',
  TOGGLE_SHOWING_PROFILE = 'TOGGLE_SHOWING_PROFILE',
}

export enum DAY {
  AFTERNOON = 'DAY_AFTERNOON',
  EVENING = 'DAY_EVENING',
  MORNING = 'DAY_MORNING',
}
